#ifndef EXERCISES_H
#define EXERCISES_H
#include "lab2.h"
#include "software_timer.h"
void exercise1_init(void);
void exercise1_tick(void);
void exercise1_poll(void);
void exercise2_init(void);
void exercise2_tick(void);
void exercise2_poll(void);
void exercise3_init(void);
void exercise3_tick(void);
void exercise3_poll(void);
void exercise4_init(void);
void exercise4_tick(void);
void exercise4_poll(void);
void exercise5_init(void);
void exercise5_tick(void);
void exercise5_poll(void);
void exercise6_init(void);
void exercise6_tick(void);
void exercise6_poll(void);
void exercise7_init(void);
void exercise7_tick(void);
void exercise7_poll(void);
void exercise8_init(void);
void exercise8_tick(void);
void exercise8_poll(void);
void exercise9_init(void);
void exercise9_tick(void);
void exercise9_poll(void);
void exercise10_init(void);
void exercise10_tick(void);
void exercise10_poll(void);
#endif
